In [1]:
#array sum
import numpy as np

marks = np.array([56, 83, 76,40])

print(marks.sum())



255


In [3]:
#array place
import numpy as np

arr = np.array([3, 7, 5])

print(arr)
print(arr[0])
print(arr[1])
print(arr[2])

[3 7 5]
3
7
5


In [9]:
#array calculation
import numpy as np
a=np.array([10,20,30])
b=np.array([45,67,45])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[55 87 75]
[-35 -47 -15]
[ 450 1340 1350]
[0.22222222 0.29850746 0.66666667]


In [8]:
import numpy as np

a = np.array([88, 64, 72])
b = np.array([56, 69, 95])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)


Addition: [144 133 167]
Subtraction: [ 32  -5 -23]
Multiplication: [4928 4416 6840]


In [10]:
#find maximum and minimum
import numpy as np
a=np.array([65,97,52])
b=np.array([78,56,56])
max=np.maximum(a,b)
print("maximum value:",max)
min=np.minimum(a,b)
print("minimum value:",min)

maximum value: [78 97 56]
minimum value: [65 56 52]
